setReactiveValuesToDefault <- function(reactVals){
  reactVals$cSpPOIP <- ""
  reactVals$cColsPOIP <- ""
  reactVals$cSpPOIL <- ""
  reactVals$cColsPOIL <- ""
  reactVals$cSpPOIPg <- ""
  reactVals$cColsPOIPg <- ""
  reactVals$cSpPlEP <- ""
  reactVals$cColsPlEP <- ""
  reactVals$cSpPlEL <- ""
  reactVals$cColsPlEL <- ""
  reactVals$cSpPlEPg <- ""
  reactVals$cColsPlEPg <- ""
  reactVals$cSpNetP <- ""
  reactVals$cColsNetP <- ""
  reactVals$cSpNetL <- ""
  reactVals$cColsNetL <- ""
  reactVals$cSpNetPg <- ""
  reactVals$cColsNetPg <- ""
  reactVals$cSpEnvP <- ""
  reactVals$cColsEnvP <- ""
  reactVals$cSpEnvL <- ""
  reactVals$cColsEnvL <- ""
  reactVals$cSpEnvPg <- ""
  reactVals$cColsEnvPg <- ""
  reactVals$cSpResP <- ""
  reactVals$cColsResP <- ""
  reactVals$cSpResL <- ""
  reactVals$cColsResL <- ""
  reactVals$cSpResPg <- ""
  reactVals$cColsResPg <- ""
  reactVals$Res_att <- Res_att
  reactVals$POI_att <- POI_att
  reactVals$PlE_att <- PlE_att
  reactVals$Net_att <- Net_att
  reactVals$Env_att <- Env_att
  reactVals$Res_att_nice <- Res_att_nice
  reactVals$POI_att_nice <- POI_att_nice
  reactVals$PlE_att_nice <- PlE_att_nice
  reactVals$Net_att_nice <- Net_att_nice
  reactVals$Env_att_nice <- Env_att_nice
  reactVals$lan <- lan
  reactVals$nRules <- 1
  reactVals$addXvar <- ""
  reactVals$lastRule <- ""
  reactVals$activeRule <- paste("tabPanel_rule", 1, sep = "_")
  reactVals$lastXvar <- ""
  reactVals$lastXvar_id <- ""
  reactVals$lastXvar_sel <- addText
  reactVals$lastYvar_sel <- plsChoose
  reactVals$allRuleParameters <- allRuleParameters
  reactVals$yOverview <- yOverview
  reactVals$sumTab <- ""
  reactVals$gamePoints <- gamePoints
  reactVals$gameActionPoints <- gameActionPoints
  reactVals$timestep <- timestep
  reactVals$temp_fac <- ""
  reactVals$clicked <- NULL
  reactVals$modDat <- modDat
  reactVals$gaugeVals <- ""
  reactVals$allAnalAtts <- ""
  reactVals$gameScoreVals_noAct <- gameScoreVals_noAct
  reactVals$before_Gauges <- before_Gauges
  
  reactVals <<- reactVals
}